default_agent: mfstSharepointMcp
agents:
  mfstSharepointMcp:
    name: mfstSharepointMcp
    language: python
    node_version: '20'
    entrypoint: src/mfst_agent_runtime/sharepoint_mcp/app.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/adhuy/code/led8/ai/spark/voidm
    aws:
      execution_role: arn:aws:iam::160885283756:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-67e5da90d5
      execution_role_auto_create: false
      account: '160885283756'
      region: us-east-1
      ecr_repository: 160885283756.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-mfstsharepointmcp
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: MCP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: mfstSharepointMcp_mem-61aUdOGG24
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:160885283756:memory/mfstSharepointMcp_mem-61aUdOGG24
      memory_name: mfstSharepointMcp_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        discoveryUrl: https://login.microsoftonline.com/e01bd386-fa51-4210-a2a4-29e5ab6f7ab1/.well-known/openid-configuration
        allowedAudience:
        - api://2ba65c62-10b1-400f-971f-1fa63fce8b7b
    request_header_configuration:
      requestHeaderAllowlist:
      - Authorization
      - X-Amzn-Bedrock-AgentCore-Runtime-Custom-Correlation-Id
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
