name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Initialize models
        run: cargo run --release --bin voidm -- init

      - name: Test
        run: cargo test --release -- --test-threads=4
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13"

